# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: DuckHunTrix
theme:
  font: false  # get rid of google fonts
  icon:
    repo: fontawesome/brands/git-alt
  name: material

repo_name: DuckHunt/DuckHunTrix
repo_url: https://codeberg.org/DuckHunt/DuckHunTrix
